### PR TITLE
fix handling of import lists, closes #9

### LINKED ISSUE #9: `import` keyword missing in output
in:
```scala
import argonaut._, Argonaut._
import scala.util.Try

object Bug {
  def apply() = Try(Json.obj("foo" := "bar"))
}
```

out:
```scala
scala.util.Try

import import argonaut._, Argonaut._

object Bug {
  def apply() = Try(Json.obj("foo" := "bar"))
}

```

conf:
```js
SortImports.blocks = [
  "scala.",
  "*",
]
```

### PR DESCRIPTION
**Pull request by tuures**
Previously `Import` nodes with one children (one `Importer` node) were flattened to to that `Importer` node while `Import` nodes with more children were not. Now there's no flattening. Instead the whole `Import` nodes (essentially import lines) are carried through the processing. 

When sorting and grouping the import lines, the first import element (`Importer` node) in the import line is used as the "key" that determines the the grouping and sorting of the whole line.

### CODE REVIEW

File: scalafix/input/src/main/scala/fix/importlist.scala [hunk 1]
```diff
@@ -5,11 +5,11 @@
  "scala"
  ]
  */
+import scala.collection._, scala.util._
```
Comment (NeQuissimus) [inline scalafix/input/src/main/scala/fix/importlist.scala]: Considering the `blocks` directive up top, why would this come first?

**Comment by NeQuissimus** [comment]
Can you add your example from the issue as a test?

Edit: Ah, nvm, it would require us loading the dependency. The test change should cover the same thing.
Thanks for this!
